Implement zxing
zcash/zcash-android-wallet pull request #232
Opened 2021-02-14 22:04 UTC by herou

Replace the firebase implementation with zxing implementation
Note: In progress

2021-02-14 22:05 UTC, herou commented
@gmale Still in progress.

2021-02-21 12:49 UTC, herou commented
@gmale Please, review this ticket.

2021-02-24 01:24 UTC, gmale requested changes

2021-02-24 01:24 UTC, gmale commented on app/src/main/java/cash/z/ecc/android/ui/scan/QrAnalyzer.kt
> +    private val reader =  MultiFormatReader()
We can use a `QRCodeReader` here instead since we don't read any other kind of barcodes.

2021-02-24 01:24 UTC, gmale commented on app/src/main/java/cash/z/ecc/android/ui/scan/QrAnalyzer.kt
>      override fun analyze(image: ImageProxy) {
This analyze code did not work for me. I found a few other implementations online that worked fairly well like [this simple one from google glass](https://github.com/googlesamples/glass-enterprise-samples/blob/87042eec1e619b874182b25236f2d49357bc92e0/QRCodeScannerSample/app/src/main/java/com/example/glass/qrcodescannersample/QRCodeImageAnalysis.java#L69-L85) but I haven't yet found one that works for [QRs on zecpages](https://www.z2z.to/) because they don't use standard QR colors. Even converting the image to black and white doesn't seem to help.

I'll try to keep poking around to either find or write some logic that can handle odd colors. We may need to invert the zecpages colors first and then try decoding both versions of the bitmap, whenever we scan QR codes.

2021-02-24 01:24 UTC, gmale commented on app/build.gradle
> +    implementation 'com.journeyapps:zxing-android-embedded:3.6.0'
this can be added to the [// Misc.](https://github.com/zcash/zcash-android-wallet/blob/5f713454d3d3428bf2b0c98130992830ca30ae18/app/build.gradle#L171-L173) section so that we use the same scanner in the app as well as the qrecycler module:
```
 implementation Deps.Misc.Plugins.QR_SCANNER
```

2021-02-24 02:43 UTC, gmale commented on app/src/main/java/cash/z/ecc/android/ui/scan/QrAnalyzer.kt
>      override fun analyze(image: ImageProxy) {
I exported what the QR decoder sees and I can confirm that it inverts the zecpages colors in a way that is not scannable:

<img src="https://user-images.githubusercontent.com/1699841/108939638-029ff300-7620-11eb-9120-c34105262e3f.png" width=380>


So next, I will work on inverting the image whenever scan fails and that should fix the scanner for zecpages (and others who use custom colors).

2021-02-24 03:08 UTC, gmale commented on app/src/main/java/cash/z/ecc/android/ui/scan/QrAnalyzer.kt
>      override fun analyze(image: ImageProxy) {
Inverting the bitmap worked! Now the image scans. I'll clean up the code I have and post it in a comment, shortly:

<img src="https://user-images.githubusercontent.com/1699841/108941603-6677eb00-7623-11eb-9157-54e98b25ecc3.png" width=440>

2021-02-24 04:44 UTC, gmale commented on app/src/main/java/cash/z/ecc/android/ui/scan/QrAnalyzer.kt
>      override fun analyze(image: ImageProxy) {
I've updated the `analyze` function to this and it successfully scans both QR codes in the comments above. Anytime a scan fails, it simply inverts the image and trys again.

```kotlin
    override fun analyze(image: ImageProxy) {
        image.toBinaryBitmap().let { bitmap ->
            val qrContent = bitmap.decodeWith(reader) ?: bitmap.flip().decodeWith(reader)
            if (qrContent == null) {
                image.close()
            } else {
                onImageScan(qrContent, image)
            }
        }
    }
```

And here are the related extension functions:
```kotlin
    private fun ImageProxy.toBinaryBitmap(): BinaryBitmap {
        return planes[0].buffer.let { buffer ->
            ByteArray(buffer.remaining()).also { buffer.get(it) }
        }.let { bytes ->
            PlanarYUVLuminanceSource(bytes, width, height, 0, 0, width, height, false)
        }.let { source ->
            BinaryBitmap(HybridBinarizer(source))
        }
    }

    private fun BinaryBitmap.decodeWith(reader: Reader): String? {
        return try {
            reader.decode(this).toString()
        } catch (e: NotFoundException) {
            // these happen frequently. Whenever no QR code is found in the frame. No need to log.
            null
        } catch (e: Throwable) {
            twig("Error while scanning QR: $e")
            null
        }
    }

    private fun BinaryBitmap.flip(): BinaryBitmap {
        blackMatrix.apply {
            repeat(width) { w ->
                repeat(height) { h ->
                    flip(w, h)
                }
            }
        }
        return this
    }
```

2021-02-28 17:39 UTC, herou commented
@gmale  I applied the above requests. Please review them!

2021-02-28 21:01 UTC, nighthawk24 commented on buildSrc/src/main/java/cash/z/ecc/android/Dependencies.kt
> +                val VIEW =                  "androidx.camera:camera-view:1.0.0-alpha21"
Preferable to use `$version` as the Version() is set for the object.

And the formatting can be improved for L32

2021-02-28 21:02 UTC, nighthawk24 commented on app/src/main/java/cash/z/ecc/android/ui/scan/QrAnalyzer.kt
> +import com.google.zxing.*
Try avoiding wildcard imports as the strict-kotlin lint does not like it.

2021-03-01 18:52 UTC, gmale commented on buildSrc/src/main/java/cash/z/ecc/android/Dependencies.kt
> +                val VIEW =                  "androidx.camera:camera-view:1.0.0-alpha21"
Yes. Good catch!

2021-03-01 18:54 UTC, gmale commented
Completed quick review of latest changes. Overall those changes look good to me. I need to dig into this a bit further and test locally.

2021-03-14 04:39 UTC, nighthawk24 commented
@gmale is this branch good to merge?

2021-03-16 18:32 UTC, gmale commented
It needs a few minor changes but since it has it has been open for a long while (and that's totally my fault BTW, Elio has been great) I'll merge it and make those changes, now, because that's fastest.

2021-03-16 18:32 UTC, merged

2021-03-16 19:10 UTC, gmale commented on app/src/main/java/cash/z/ecc/android/ui/scan/QrAnalyzer.kt
> +    private val reader =  MultiFormatReader()
Addressed in dfc6838bdf7fff6416bf0ad257db30d223ecdcb1

2021-03-16 19:16 UTC, gmale commented on buildSrc/src/main/java/cash/z/ecc/android/Dependencies.kt
> +                val VIEW =                  "androidx.camera:camera-view:1.0.0-alpha21"
Addressed in f60ed7dd2bb4ed82dd21a9b5d6acffd31f8a567f

2021-03-16 19:16 UTC, gmale commented on app/src/main/java/cash/z/ecc/android/ui/scan/QrAnalyzer.kt
> +import com.google.zxing.*
addressed in dfc6838bdf7fff6416bf0ad257db30d223ecdcb1

2021-03-16 19:19 UTC, gmale commented
Everything has been addressed and I ran the build and confirmed that it still scans both QRs on this page (the normal and inverted).

Note @nighthawk24 this required a [placeholder implementation](3bf1ed1415c1fcd422aee9f6e8452b2ec518b8c4) of ZIP-321. In the near future, we'd like to directly use @nuttycom 's implementation in the Rust crates. We just have to figure out how to represent the parsed data across the FFI for both iOS and Android. We have a few ideas but haven't yet prioritized that work.