New design for Wallet History
zcash/zcash-android-wallet pull request #249
Opened 2021-04-11 19:29 UTC by MandeepDaffo

![Screenshot_20210412-005334_ECC Wallet](https://user-images.githubusercontent.com/72556520/114318282-1a78fb00-9b2a-11eb-98cf-00c8339f2681.jpg)

2021-04-12 20:54 UTC, gmale requested changes
@Mandeepbhalothia 
Wow. Thanks for the quick turn around time and even putting in work over the weekend. I appreciate the efforts! Thanks for investing your time. I reviewed the code and also paired with the designer to get his feedback.

First, this is pretty much exactly what was expected and more!

Next, here is a quick summary of his feedback:
- Blue is a new color that will be coming to the app and get heavy use for anything "transparent" (i.e. not shielded, using an address that starts with a `t`)
- For a given history item:
    - the `amount` should be:
        - red if negative
        - yellow if shielded (and positive)
        - white if positive (and not shielded)
        - _Implementation Note: "shielded" here is defined as_ `transaction.toAddress.isShielded()`.
    - the `address` should be:
        - white, unless transparent
    - if the transaction is shielded, everything is yellow, like this (to indicate this is preferred):
    - <img src="https://user-images.githubusercontent.com/1699841/114459692-dc71ea80-9bae-11eb-8b2c-05fd3d958681.png" width=320/>
    - the left-side bar should be:
        - blue if to or from a transparent address
        - yellow if to or from a shielded address
        - gray if pending (matching the date/time color)
- The designer thought the right-aligned memo icon was a nice touch because it's always in the same place
- The header area will probably change but he wants to make clear designs for that rather than just giving feedback. So what you have for now is great.

2021-04-12 20:54 UTC, gmale commented on app/src/main/res/layout/fragment_history.xml
> +    android:background="@color/zcashBlack_0">
The design was a little chopped off so it's hard to see that this background was intended to be the same. This line edit can be reverted.

2021-04-13 12:17 UTC, Mandeepbhalothia commented on app/src/main/res/layout/fragment_history.xml
> +    android:background="@color/zcashBlack_0">
Thanks @gmale for sharing the the description related to colour combinations. Hope now we can cover all combinations!
Yes I will check this background thing also.

2021-04-13 16:07 UTC, Mandeepbhalothia commented
@gmale Please review the PR. Design is completed by taking conditions from your above comment. Sorry I don't have access to change this Draft PR to ready for review.

2021-04-16 18:37 UTC, gmale commented
The code looks good to me. Testing all the scenarios is a little tricky and time consuming. So for the sake of moving forward, I'll merge this and then if we get any additional feedback from the designer or spot any issues, I'll just open issues for that work.

2021-04-16 18:37 UTC, merged