302 sdk 1.10
zcash/zcash-android-wallet pull request #348
Opened 2022-11-02 11:07 UTC by gasstan

2022-11-03 17:29 UTC, ccjernigan requested changes
Thanks for adopting the SDK api changes!  I noted a few minor things that we'll need to update.

2022-11-03 17:29 UTC, ccjernigan commented on app/src/main/java/cash/z/ecc/android/di/SynchronizerComponent.kt
> +        alias: String = "zcash",
We should double-check what alias was used before, because this could break client upgrades.

2022-11-03 17:29 UTC, ccjernigan commented on app/src/main/java/cash/z/ecc/android/ui/history/HistoryViewModel.kt
> +                        //address = tx?.toAddress TODO waiting for sdk
Exists in SDK now.

2022-11-07 13:54 UTC, gasstan commented on app/src/main/java/cash/z/ecc/android/ui/home/BalanceDetailViewModel.kt
> +import cash.z.ecc.android.sdk.model.*
i've already updated my setting not sure how this got there

2023-01-10 18:36 UTC, pacu approved these changes
utACK
I went through the code to check that changes correspond to the scope of the API changes to maintain current functionality of the reference wallet

2023-01-11 08:32 UTC, HonzaR approved these changes
I just optimized imports across the project and run and tested the app and it seems to be working as expected.

2023-01-11 12:43 UTC, pacu approved these changes

2023-01-11 18:59 UTC, ccjernigan requested changes
I have two minor changes that we should address.

2023-01-11 18:59 UTC, ccjernigan commented on app/src/main/java/cash/z/ecc/android/ui/send/SendFinalFragment.kt
> +            lifecycleScope.launchWhenStarted {
`launchWhenStarted` is deprecated.  Replacement is `lifecycleScope.launch{repeatOnLifeCycle() {...} }`

2023-01-11 18:59 UTC, ccjernigan commented on app/src/main/java/cash/z/ecc/android/ui/profile/ProfileViewModel.kt
> +        synchronizer.close()
We have a problem here—once the synchronizer is closed we actually need to clear the global synchronizer and start over.  There's not a good way to do that in this app's architecture.  We might need to call system.exit() at the end of this method (after the wipe completes).  Otherwise users will not be able to relaunch the app easily.

2023-01-18 19:24 UTC, pacu approved these changes
utAck

2023-01-18 20:36 UTC, ccjernigan requested changes

2023-01-24 18:44 UTC, pacu approved these changes
utACK

2023-01-24 19:47 UTC, pacu approved these changes
utACK

2023-01-24 19:50 UTC, ccjernigan approved these changes

2023-01-24 19:50 UTC, merged